# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ada8c69af687a620bbc701fef193a81fb0d1a7b3f2582fade84f40a7d3f77433ad527b52af377c58884356dbad44f4f69b653d5a2ac8cb391e9a8b923a5cdf8a

test:
  secret_key_base: f0f965db2adff6148bc7f164804182579fadc1fc3b3108a56daaf66d24763a3d7c9ff06fa36b262e8b3b598efda768f05b2c027e0c95e77016d746d8d81eb297

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
